### ISSUE TITLE
"GAN in Five Minutes" with my own images

### ISSUE THREAD

**Issue by me2beats** [johnolafenwa/TorchFusion#4]
Could you please explain how to generate dataset from my own images 128x128 and use "GAN in Five Minutes" with it? Any type of GAN and other params, just for quick start

**Comment by johnolafenwa** [comment]
Hi @me2beats , all you just need to do is to change the data loading part. Here is an example below, this assuming you have a folder with images

`import matplotlib
matplotlib.use('Agg')

from torchfusion.gan.learners import *
from torchfusion.gan.applications import StandardGenerator,StandardProjectionDiscriminator
from torch.optim import Adam
from torchfusion.datasets import pathimages_loader
import torch.cuda as cuda
import torch.nn as nn
import torch.backends.cudnn as cudnn

cudnn.benchmark = True

G = StandardGenerator(output_size=(3,64,64),latent_size=128)
D = StandardProjectionDiscriminator(input_size=(3,64,64),apply_sigmoid=False)

if cuda.is_available():
    G = nn.DataParallel(G.cuda())
    D = nn.DataParallel(D.cuda())

g_optim = Adam(G.parameters(),lr=0.0002,betas=(0.5,0.999))
d_optim = Adam(D.parameters(),lr=0.0002,betas=(0.5,0.999))

dataset = pathimages_loader(image_paths=["myimagefolder"],size=64,batch_size=64)

learner = RAvgHingeGanLearner(G,D)

if __name__ == "__main__":
    learner.train(dataset,gen_optimizer=g_optim,disc_optimizer=d_optim,num_epochs=1000,model_dir="./mmodelfolder",save_outputs_interval=500,latent_size=128,batch_log=True)
`
