### ISSUE TITLE
 ImportError: cannot import name 'find_classes' from 'torchvision.datasets.folder' (A:\python\envs\pyt-cpu\lib\site-packages\torchvision\datasets\folder.py)

### ISSUE THREAD

**Issue by navidpanchi** [johnolafenwa/TorchFusion#9]
When I am trying to import standard Learner I am getting the above error.

**Comment by deklesen** [comment]
I have the same problem. Did you figure out what the issue was?

**Comment by singhalanirudh18** [comment]
I am having the same problem. Any update?

**Comment by johnolafenwa** [comment]
Hello @navidpanchi @deklesen @singhalanirudh18 , sorry this issue was not fixed for so long, it has been fixed in commit 0ca7b02ed4a487a3297b5bca28911116b29e701d 

Note also that further development of this project is resuming soon. Thanks for your patience
